# Generated by Django 5.1.7 on 2025-03-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='photo',
            name='camera',
            field=models.CharField(default='Fuji X-T50', max_length=200),
        ),
        migrations.AddField(
            model_name='photo',
            name='simulation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
