# Generated by Django 5.1.7 on 2025-03-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_photo_thumbnail_photo_camera_photo_simulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter',
        ),
    ]
