# Generated by Django 5.1.7 on 2025-03-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_contact_facebook_remove_contact_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
