# Generated by Django 5.1.7 on 2025-03-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contact_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/thumbnails/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='photos/webp/'),
        ),
    ]
